FROM debian:buster-slim as rusty
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git clang curl libssl-dev llvm libudev-dev make protobuf-compiler pkg-config && rm -rf /var/lib/apt/lists/*
RUN curl https://sh.rustup.rs -sSf | CARGO_HOME=/usr/local RUSTUP_HOME=/usr/local sh -s -- -y
RUN rustup default stable
RUN rustup target add wasm32-unknown-unknown
WORKDIR /app

FROM rusty as builder
COPY substrate/ .
RUN cargo build --release

FROM debian:buster-slim AS runtime
EXPOSE 30333 9944
VOLUME /data
COPY --from=builder /app/target/release/substrate /node
RUN useradd -Ms /bin/bash liberland
RUN mkdir /data && chown liberland:liberland -R /node /data
USER liberland
ENTRYPOINT [ "/node" ]
