[package]
name = "kitchensink-runtime"
version = "28.0.0"
authors.workspace = true
description = "Liberland node runtime."
edition.workspace = true
build = "build.rs"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]

# third-party dependencies
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
static_assertions = "1.1.0"
log = { version = "0.4.17", default-features = false }
serde = { version = "1.0.188", default-features = false, features = ["alloc", "derive"]}

# pallet-asset-conversion: turn on "num-traits" feature
primitive-types = { version = "0.12.0", default-features = false, features = ["codec", "scale-info", "num-traits"] }

# primitives
sp-authority-discovery = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-consensus-babe = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-consensus-grandpa = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-block-builder = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
node-primitives = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-offchain = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-core = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-std = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-api = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-runtime = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-staking = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-storage = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-session = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-transaction-pool = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-version = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }
sp-io = { default-features = false, tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk" }

# frame dependencies
frame-executive = { path = "../../../frame/executive", default-features = false}
frame-benchmarking = { path = "../../../frame/benchmarking", default-features = false}
frame-benchmarking-pallet-pov = { path = "../../../frame/benchmarking/pov", default-features = false}
frame-metadata-hash-extension = { path = "../../../frame/metadata-hash-extension", default-features = false }
frame-support = { path = "../../../frame/support", default-features = false, features = ["tuples-96"] }
frame-system = { path = "../../../frame/system", default-features = false}
frame-system-benchmarking = { path = "../../../frame/system/benchmarking", default-features = false, optional = true }
frame-election-provider-support = { path = "../../../frame/election-provider-support", default-features = false}
frame-system-rpc-runtime-api = { path = "../../../frame/system/rpc/runtime-api", default-features = false}
frame-try-runtime = { path = "../../../frame/try-runtime", default-features = false, optional = true }
pallet-alliance = { path = "../../../frame/alliance", default-features = false}
pallet-asset-conversion = { path = "../../../frame/asset-conversion", default-features = false}
pallet-asset-rate = { path = "../../../frame/asset-rate", default-features = false}
pallet-assets = { path = "../../../frame/assets", default-features = false}
pallet-authority-discovery = { path = "../../../frame/authority-discovery", default-features = false}
pallet-authorship = { path = "../../../frame/authorship", default-features = false}
pallet-babe = { path = "../../../frame/babe", default-features = false}
pallet-bags-list = { path = "../../../frame/bags-list", default-features = false}
pallet-balances = { path = "../../../frame/balances", default-features = false}
pallet-bounties = { path = "../../../frame/bounties", default-features = false}
pallet-broker = { path = "../../../frame/broker", default-features = false}
pallet-child-bounties = { path = "../../../frame/child-bounties", default-features = false}
pallet-collective = { path = "../../../frame/collective", default-features = false}
pallet-contracts = { path = "../../../frame/contracts", default-features = false}
pallet-contracts-primitives = { path = "../../../frame/contracts/primitives", default-features = false}
pallet-conviction-voting = { path = "../../../frame/conviction-voting", default-features = false}
pallet-core-fellowship = { path = "../../../frame/core-fellowship", default-features = false}
pallet-democracy = { path = "../../../frame/democracy", default-features = false}
pallet-election-provider-multi-phase = { path = "../../../frame/election-provider-multi-phase", default-features = false}
pallet-election-provider-support-benchmarking = { path = "../../../frame/election-provider-support/benchmarking", default-features = false, optional = true }
pallet-elections-phragmen = { path = "../../../frame/elections-phragmen", default-features = false}
pallet-fast-unstake = { path = "../../../frame/fast-unstake", default-features = false}
pallet-nis = { path = "../../../frame/nis", default-features = false}
pallet-grandpa = { path = "../../../frame/grandpa", default-features = false}
pallet-im-online = { path = "../../../frame/im-online", default-features = false}
pallet-indices = { path = "../../../frame/indices", default-features = false}
pallet-identity = { path = "../../../frame/identity", default-features = false}
pallet-lottery = { path = "../../../frame/lottery", default-features = false}
pallet-membership = { path = "../../../frame/membership", default-features = false}
pallet-message-queue = { path = "../../../frame/message-queue", default-features = false}
pallet-mmr = { path = "../../../frame/merkle-mountain-range", default-features = false}
pallet-multisig = { path = "../../../frame/multisig", default-features = false}
pallet-nfts = { path = "../../../frame/nfts", default-features = false}
pallet-nfts-runtime-api = { path = "../../../frame/nfts/runtime-api", default-features = false}
pallet-nft-fractionalization = { path = "../../../frame/nft-fractionalization", default-features = false}
pallet-nomination-pools = { path = "../../../frame/nomination-pools", default-features = false}
pallet-nomination-pools-benchmarking = { path = "../../../frame/nomination-pools/benchmarking", default-features = false, optional = true}
pallet-nomination-pools-runtime-api = { path = "../../../frame/nomination-pools/runtime-api", default-features = false}
pallet-offences = { path = "../../../frame/offences", default-features = false}
pallet-offences-benchmarking = { path = "../../../frame/offences/benchmarking", default-features = false, optional = true }
pallet-glutton = { path = "../../../frame/glutton", default-features = false}
pallet-preimage = { path = "../../../frame/preimage", default-features = false}
pallet-proxy = { path = "../../../frame/proxy", default-features = false}
pallet-insecure-randomness-collective-flip = { path = "../../../frame/insecure-randomness-collective-flip", default-features = false}
pallet-ranked-collective = { path = "../../../frame/ranked-collective", default-features = false}
pallet-recovery = { path = "../../../frame/recovery", default-features = false}
pallet-referenda = { path = "../../../frame/referenda", default-features = false}
pallet-remark = { path = "../../../frame/remark", default-features = false}
pallet-root-testing = { path = "../../../frame/root-testing", default-features = false}
pallet-salary = { path = "../../../frame/salary", default-features = false}
pallet-session = { path = "../../../frame/session", default-features = false , features = [ "historical" ]}
pallet-session-benchmarking = { path = "../../../frame/session/benchmarking", default-features = false, optional = true }
pallet-staking = { path = "../../../frame/staking", default-features = false}
pallet-staking-reward-curve = { path = "../../../frame/staking/reward-curve", default-features = false}
pallet-staking-runtime-api = { path = "../../../frame/staking/runtime-api", default-features = false}
pallet-state-trie-migration = { path = "../../../frame/state-trie-migration", default-features = false}
pallet-statement = { path = "../../../frame/statement", default-features = false}
pallet-scheduler = { path = "../../../frame/scheduler", default-features = false}
pallet-society = { path = "../../../frame/society", default-features = false}
pallet-sudo = { path = "../../../frame/sudo", default-features = false}
pallet-timestamp = { path = "../../../frame/timestamp", default-features = false}
pallet-tips = { path = "../../../frame/tips", default-features = false}
pallet-treasury = { path = "../../../frame/treasury", default-features = false}
pallet-utility = { path = "../../../frame/utility", default-features = false}
pallet-transaction-payment = { path = "../../../frame/transaction-payment", default-features = false}
pallet-transaction-payment-rpc-runtime-api = { path = "../../../frame/transaction-payment/rpc/runtime-api", default-features = false}
pallet-asset-conversion-tx-payment = { path = "../../../frame/transaction-payment/asset-conversion-tx-payment", default-features = false}
pallet-asset-tx-payment = { path = "../../../frame/transaction-payment/asset-tx-payment", default-features = false}
pallet-transaction-storage = { path = "../../../frame/transaction-storage", default-features = false}
pallet-uniques = { path = "../../../frame/uniques", default-features = false}
pallet-vesting = { path = "../../../frame/vesting", default-features = false}
pallet-whitelist = { path = "../../../frame/whitelist", default-features = false}
pallet-tx-pause = { path = "../../../frame/tx-pause", default-features = false}
pallet-safe-mode = { path = "../../../frame/safe-mode", default-features = false}

# Sora Bridge:
substrate-bridge-app = { git = "https://github.com/sora-xor/sora2-common.git", branch = "polkadotsdk-lib-1.1.0", default-features = false }
substrate-bridge-channel = { git = "https://github.com/sora-xor/sora2-common.git", branch = "polkadotsdk-lib-1.1.0", default-features = false }
leaf-provider = { git = "https://github.com/sora-xor/sora2-common.git", branch = "polkadotsdk-lib-1.1.0", default-features = false }
dispatch = { git = "https://github.com/sora-xor/sora2-common.git", branch = "polkadotsdk-lib-1.1.0", default-features = false }
bridge-data-signer = { git = "https://github.com/sora-xor/sora2-common.git", branch = "polkadotsdk-lib-1.1.0", default-features = false }
multisig-verifier = { git = "https://github.com/sora-xor/sora2-common.git", branch = "polkadotsdk-lib-1.1.0", default-features = false }
bridge-types = { git = "https://github.com/sora-xor/sora2-common.git", branch = "polkadotsdk-lib-1.1.0", default-features = false }
sora-liberland-bridge-provider = { git = "https://github.com/sora-xor/sora2-common.git", branch = "polkadotsdk-lib-1.1.0", default-features = false, package = "liberland-bridge-provider" }

[build-dependencies]
substrate-wasm-builder = { tag = "polkadot-v1.1.0", git = "https://github.com/paritytech/polkadot-sdk", optional = true}

[features]
default = ["std"]
testnet-runtime = []
with-tracing = [ "frame-executive/with-tracing" ]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-election-provider-support/std",
	"frame-executive/std",
	"frame-metadata-hash-extension/std",
	"frame-support/std",
	"frame-system-benchmarking?/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"frame-try-runtime?/std",
	"liberland-extension-runtime/std",
	"log/std",
	"node-primitives/std",
	"pallet-asset-conversion/std",
	"pallet-asset-conversion-tx-payment/std",
	"pallet-assets/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"pallet-babe/std",
	"pallet-bags-list/std",
	"pallet-balances/std",
	"pallet-collective/std",
	"pallet-contracts-primitives/std",
	"pallet-contracts-registry/std",
	"pallet-contracts/std",
	"pallet-custom-account/std",
	"pallet-democracy/std",
	"pallet-election-provider-multi-phase/std",
	"pallet-election-provider-support-benchmarking?/std",
	"pallet-elections-phragmen/std",
	"pallet-grandpa/std",
	"pallet-identity/std",
	"pallet-im-online/std",
	"pallet-liberland-initializer/std",
	"pallet-liberland-legislation/std",
	"pallet-llm/std",
	"pallet-membership/std",
	"pallet-multisig/std",
	"pallet-nfts-runtime-api/std",
	"pallet-nfts/std",
	"pallet-offences-benchmarking?/std",
	"pallet-offences/std",
	"pallet-office/std",
	"pallet-preimage/std",
	"pallet-proxy/std",
	"pallet-registry/std",
	"pallet-scheduler/std",
	"pallet-session-benchmarking?/std",
	"pallet-session/std",
	"pallet-staking-runtime-api/std",
	"pallet-staking/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-storage/std",
	"pallet-treasury/std",
	"pallet-utility/std",
	"scale-info/std",
	"sp-api/std",
	"sp-authority-discovery/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-consensus-grandpa/std",
	"sp-core/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"substrate-wasm-builder",

	# Sora Bridge:
	"substrate-bridge-app/std",
	"substrate-bridge-channel/std",
	"leaf-provider/std",
	"dispatch/std",
	"bridge-data-signer/std",
	"bridge-types/std",
	"multisig-verifier/std",
	"sora-liberland-bridge-provider/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-bags-list/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-contracts-registry/runtime-benchmarks",
	"pallet-contracts/runtime-benchmarks",
	"pallet-custom-account/runtime-benchmarks",
	"pallet-democracy/runtime-benchmarks",
	"pallet-election-provider-multi-phase/runtime-benchmarks",
	"pallet-election-provider-support-benchmarking/runtime-benchmarks",
	"pallet-elections-phragmen/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-liberland-legislation/runtime-benchmarks",
	"pallet-llm/runtime-benchmarks",
	"pallet-membership/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-nfts/runtime-benchmarks",
	"pallet-offences-benchmarking/runtime-benchmarks",
	"pallet-offences/runtime-benchmarks",
	"pallet-office/runtime-benchmarks",
	"pallet-preimage/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-registry/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"pallet-session-benchmarking/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-transaction-storage/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",

	# Sora Bridge
	"dispatch/runtime-benchmarks",
	"multisig-verifier/runtime-benchmarks",
]
try-runtime = [
	"frame-election-provider-support/try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"frame-try-runtime/try-runtime",
	"pallet-asset-conversion-tx-payment/try-runtime",
	"pallet-asset-conversion/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-authority-discovery/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-bags-list/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-contracts-registry/try-runtime",
	"pallet-contracts/try-runtime",
	"pallet-custom-account/try-runtime",
	"pallet-democracy/try-runtime",
	"pallet-election-provider-multi-phase/try-runtime",
	"pallet-elections-phragmen/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-identity/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-liberland-initializer/try-runtime",
	"pallet-liberland-legislation/try-runtime",
	"pallet-llm/try-runtime",
	"pallet-membership/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-nfts/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-office/try-runtime",
	"pallet-preimage/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-registry/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-transaction-storage/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-utility/try-runtime",
	"sp-runtime/try-runtime",

	# Sora Bridge:
	"substrate-bridge-app/try-runtime",
	"substrate-bridge-channel/try-runtime",
	"leaf-provider/try-runtime",
	"dispatch/try-runtime",
	"bridge-data-signer/try-runtime",
	"bridge-types/try-runtime",
	"multisig-verifier/try-runtime",
	"sora-liberland-bridge-provider/try-runtime",
]

metadata-hash = ["substrate-wasm-builder/metadata-hash"]
