[package]
name = "liberland-extension-runtime"
version = "1.0.0"
authors.workspace = true
description = "Liberland chain extension."
edition.workspace = true
license = "MIT"
repository.workspace = true
publish = false

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false }
frame-support = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
pallet-contracts = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-std = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-core = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
frame-system = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0" }
log = { version = "0.4.17", default-features = false }

pallet-llm = { default-features = false, path = "../../substrate/frame/llm" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"pallet-contracts/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-system/std",
	"log/std",
	"pallet-llm/std",
]