FROM debian:bullseye-slim as downloader
ARG VERSION=latest 
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y curl jq && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN curl -sSL https://api.github.com/repos/liberland/liberland_substrate/releases/${VERSION} -o relinfo
RUN curl -sSL "$(jq -r '.assets[] | select(.name == "linux_x86_build") | .browser_download_url' < relinfo)" -o node

FROM debian:bullseye-slim
EXPOSE 30333 9933 9944
VOLUME /data
RUN useradd -Ms /bin/bash liberland
COPY --from=downloader /app/node /node
COPY specs /specs
RUN mkdir /data && chown liberland:liberland -R /specs /node /data && chmod +x /node
USER liberland
ENTRYPOINT [ "/node" ]
