name: Build & publish Docker image

on:
  release:
    types: [released]

jobs:
  build-and-publish-docker:
    permissions: 
        packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
            context: .
            file: Dockerfile-prebuilt
            push: true
            build-args: VERSION=tags/${{ github.ref_name }}
            tags: ghcr.io/liberland/blockchain-node:${{ github.ref_name }},ghcr.io/liberland/blockchain-node:latest