name: Build runtimes & draft release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  srtool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.6.0
        with:
          chain: liberland
          package: kitchensink-runtime
          runtime_dir: ./bin/node/runtime

      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > liberland-srtool-digest.json
          cat liberland-srtool-digest.json
          cp "${{ steps.srtool_build.outputs.wasm_compressed }}" ./mainnet-${{github.ref_name}}.compact.compressed.wasm
          ls
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: mainnet-${{github.ref_name}}.compact.compressed.wasm